### PR TITLE
Added Shreejan Joshi

### PR DESCRIPTION
**Pull request by shreejan1212**
This pull request adds Shreejan Joshi as a student.

### CODE REVIEW

**Review by alessandroaussems — CHANGES_REQUESTED** [review]
Add yourself to the README.md see Contributing.md for more details

**Comment by alessandroaussems** [comment]
@shreejan1212 Please fix feedback 🙂

**Comment by shreejan1212** [comment]
Add myself to the README.md

**Comment by alessandroaussems** [comment]
Welcome to the club! 🎉

**Pull request merged**
